/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we\'ve switched to the design first approach! You can now help us improve the API whether it\'s by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you\'re looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Order } from '../models/index';
import { OrderFromJSON, OrderToJSON } from '../models/index';

export interface DeleteOrderRequest {
  orderId: number;
}

export interface GetOrderByIdRequest {
  orderId: number;
}

export interface PlaceOrderRequest {
  order?: Order;
}

/**
 * StoreApi - interface
 *
 * @export
 * @interface StoreApiInterface
 */
export interface StoreApiInterface {
  /**
   * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
   * @summary Delete purchase order by ID
   * @param {number} orderId ID of the order that needs to be deleted
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StoreApiInterface
   */
  deleteOrderRaw(
    requestParameters: DeleteOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
   * Delete purchase order by ID
   */
  deleteOrder(
    requestParameters: DeleteOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   * Returns a map of status codes to quantities
   * @summary Returns pet inventories by status
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StoreApiInterface
   */
  getInventoryRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<{ [key: string]: number }>>;

  /**
   * Returns a map of status codes to quantities
   * Returns pet inventories by status
   */
  getInventory(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<{ [key: string]: number }>;

  /**
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   * @summary Find purchase order by ID
   * @param {number} orderId ID of order that needs to be fetched
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StoreApiInterface
   */
  getOrderByIdRaw(
    requestParameters: GetOrderByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Order>>;

  /**
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   * Find purchase order by ID
   */
  getOrderById(
    requestParameters: GetOrderByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Order>;

  /**
   * Place a new order in the store
   * @summary Place an order for a pet
   * @param {Order} [order]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StoreApiInterface
   */
  placeOrderRaw(
    requestParameters: PlaceOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Order>>;

  /**
   * Place a new order in the store
   * Place an order for a pet
   */
  placeOrder(
    requestParameters: PlaceOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Order>;
}

/**
 *
 */
export class StoreApi extends runtime.BaseAPI implements StoreApiInterface {
  /**
   * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
   * Delete purchase order by ID
   */
  async deleteOrderRaw(
    requestParameters: DeleteOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (
      requestParameters.orderId === null ||
      requestParameters.orderId === undefined
    ) {
      throw new runtime.RequiredError(
        'orderId',
        'Required parameter requestParameters.orderId was null or undefined when calling deleteOrder.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/store/order/{orderId}`.replace(
          `{${'orderId'}}`,
          encodeURIComponent(String(requestParameters.orderId))
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
   * Delete purchase order by ID
   */
  async deleteOrder(
    requestParameters: DeleteOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteOrderRaw(requestParameters, initOverrides);
  }

  /**
   * Returns a map of status codes to quantities
   * Returns pet inventories by status
   */
  async getInventoryRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<{ [key: string]: number }>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['api_key'] = this.configuration.apiKey('api_key'); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/store/inventory`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Returns a map of status codes to quantities
   * Returns pet inventories by status
   */
  async getInventory(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<{ [key: string]: number }> {
    const response = await this.getInventoryRaw(initOverrides);
    return await response.value();
  }

  /**
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   * Find purchase order by ID
   */
  async getOrderByIdRaw(
    requestParameters: GetOrderByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Order>> {
    if (
      requestParameters.orderId === null ||
      requestParameters.orderId === undefined
    ) {
      throw new runtime.RequiredError(
        'orderId',
        'Required parameter requestParameters.orderId was null or undefined when calling getOrderById.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/store/order/{orderId}`.replace(
          `{${'orderId'}}`,
          encodeURIComponent(String(requestParameters.orderId))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OrderFromJSON(jsonValue)
    );
  }

  /**
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   * Find purchase order by ID
   */
  async getOrderById(
    requestParameters: GetOrderByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Order> {
    const response = await this.getOrderByIdRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Place a new order in the store
   * Place an order for a pet
   */
  async placeOrderRaw(
    requestParameters: PlaceOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Order>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/store/order`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: OrderToJSON(requestParameters.order),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OrderFromJSON(jsonValue)
    );
  }

  /**
   * Place a new order in the store
   * Place an order for a pet
   */
  async placeOrder(
    requestParameters: PlaceOrderRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Order> {
    const response = await this.placeOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
