/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we\'ve switched to the design first approach! You can now help us improve the API whether it\'s by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you\'re looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ModelApiResponse
 */
export interface ModelApiResponse {
  /**
   *
   * @type {number}
   * @memberof ModelApiResponse
   */
  code?: number;
  /**
   *
   * @type {string}
   * @memberof ModelApiResponse
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof ModelApiResponse
   */
  message?: string;
}

/**
 * Check if a given object implements the ModelApiResponse interface.
 */
export function instanceOfModelApiResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ModelApiResponseFromJSON(json: any): ModelApiResponse {
  return ModelApiResponseFromJSONTyped(json, false);
}

export function ModelApiResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ModelApiResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: !exists(json, 'code') ? undefined : json['code'],
    type: !exists(json, 'type') ? undefined : json['type'],
    message: !exists(json, 'message') ? undefined : json['message'],
  };
}

export function ModelApiResponseToJSON(value?: ModelApiResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.code,
    type: value.type,
    message: value.message,
  };
}
